dist: trusty

jdk:
- oraclejdk8

script: mvn -P release verify

deploy:
- provider: script
  skip_cleanup: true
  script: releng/publish/pushToBintray.sh features/net.enilink.komma.updatesite/target/repository/
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: releng/publish/pushToBintray.sh features/net.enilink.komma.updatesite/target/repository/ "$BINTRAY_USER" "$BINTRAY_API_KEY" "$BINTRAY_OWNER" snapshots
  on:
    branch: snapshots

env:
  global:
  - BINTRAY_USER: kenwenzel
  - BINTRAY_OWNER: komma
  - BINTRAY_REPO: updates
  - BINTRAY_PCK_NAME: komma
# BINTRAY_API_KEY
  - secure: O5yhJDOeJGqRAEEUF/fUZZf6ZAGv7DM1rG+v0db+o96GUZDn2vTCdI51XJW5P4ZmCCN9yGZ+XymgFBaUAPX2hXlpZY89abZ0DCcGTwbFpzieAfmzEst8plNasVyIywXWsSuMfncsXJ74knAvRVkEtEXhT7XopkvVOUB5+e0uQCi4IpfUdD5j4MD89p8jCv0FCXNP6GoXAV2zSHBNRzpMpQ2MPC4nNObP95iiz4yJ+pgrkVfRA9eT0YVxwH4+P18MPyOkOEjaWtdWqG9cT1moq904c+LPSJM9S22XWaCtQeqiKLiFGZ6mTjMxxQmhGhaRzWftK8raPR66v35BNiLVoadPuGcPeiCIPaRsPOMj/r/gaDqDpk5NXurUSrjWInuMM7SfmVImAiAtPlDYK8Wes0D/yZlkM/omhLEtgIkBTCrWNcL6GVBRFFw+OUDbpom69guJo5JERhCeySIulExMyilso0z0ZUjfJ6DpGCSipfcFdeIvUKluoBQdf7PULvLAG80WWyVukxZNyoOUVWTLquk1MyPnXlCX9XaByiga/YFG8s0oeOLNRgHSavjSc5UUhtoKqIIpsl6+RHS6GY1dghpxcWsudxuWzfrZ+edJntYXaDfUZfgYyPZVhEXUiVPztsv9Tdgk71D7ls88GHVFiUgxwRHM9C81a5MF47gnL8I=
